repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
        files: |
          (?x)^.*(\.json)$
      - id: check-yaml
        files: |
          (?x)^.*(\.yaml|\.yml)$
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: |
          ^(\.idea/workspace\.xml|.*\.svg|requirements*\.txt)$
      - id: debug-statements
      - id: mixed-line-ending
        exclude: |
          ^(\.idea/workspace\.xml|.*\.svg)$
      - id: no-commit-to-branch
        args:
          - --branch
          - main
      - id: trailing-whitespace
        exclude: |
          ^(\.idea/workspace\.xml|.*\.svg|requirements*\.txt)$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --dictionary=.codespelldictionary
          - --ignore-words=.codespellignore
  - repo: local
    hooks:
      - id: terraform
        args:
          - -check
          - -list=true
          - -no-color
          - -recursive
        entry: terraform fmt
        language: system
        name: terraform
        types: [terraform]
