name: "pull_request"

on:
  pull_request:

jobs:
  lint:
    defaults:
      run:
        shell: "bash"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
      - uses: "pre-commit/action@v3.0.1"
      - run: |
          pre-commit run \
            --all-files \
            --color=never \
            --show-diff-on-failure \
            --verbose
